### ISSUE TITLE
Sounds silly, but chests don't work.

### ISSUE THREAD

**Issue by Auntbessie** [Furgl/Infinitory#4] opened 2021-10-12 19:50 UTC
I get this mod is meant to rid off chests basically. BUT it is nice to keep storage so you have items safe and not dropped upon death. 
Upon opening a chest the UI remains normal, but the chest closes and any items inside don't stay at all unless the chest is broken.

**Comment by Furgl** [comment] 2021-10-13 14:19
You can change Infinitory to drop different items on death in the config:
`"Items to Drop on Death (when keepInventory = false) (0 = Everything, 1 = Up to a stack of each item, 2 = Up to a stack of each item in your hotbar, offhand, and armor slots)": 1`

I'm not finding any issues with chest storage and I haven't had any other reports of issues - what mods are you using? Are you able to limit the issue down to just one/two other mods?

**Comment by Auntbessie** [comment] 2021-10-13 23:48
> You can change Infinitory to drop different items on death in the config: `"Items to Drop on Death (when keepInventory = false) (0 = Everything, 1 = Up to a stack of each item, 2 = Up to a stack of each item in your hotbar, offhand, and armor slots)": 1`
> 
> I'm not finding any issues with chest storage and I haven't had any other reports of issues - what mods are you using? Are you able to limit the issue down to just one/two other mods?


I tested a while yesterday.
With only the mod installed i found some issues.
Chests work fine even sorting stacks sizes etc. BUT if your inventory gets expanded at all, chest begin to close before use, items in chest disappear, and the game crashes if enough item are in the chest.

**Comment by Furgl** [comment] 2021-10-14 16:01
Do you know a specific way to reproduce that or could you send a gif/video of it? I'm not able to reproduce any issues when expanding/shrinking the inventory with a chest open:

https://user-images.githubusercontent.com/16003461/137354395-4c169047-de90-4640-84e6-d4c1a9fbd9d1.mp4

**Comment by Furgl** [comment] 2021-11-01 16:58
Issues like this should be fixed in v1.1.2
If you're still having issues, please reopen this or create a new issue.

**Closed as completed by Furgl** 2021-11-01 16:58 UTC
